; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_32mb_8mb]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = partitions.csv
; 32MB Flash Configuration
board_upload.flash_size = 32MB
; 8MB PSRAM Configuration (Requires OPI)
board_build.arduino.memory_type = opi_opi
board_build.flash_mode = qio
; 2. Force the compiler to include debug symbols
build_type = debug
monitor_speed = 115200
; 1. Enable the decoder filter on the serial monitor
monitor_filters = esp32_exception_decoder

build_flags = 
	-DBOARD_HAS_PSRAM
    ; -mfix-esp32-psram-cache-issue  ; (optional, for specific cache issues)
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
	mathieucarbou/AsyncTCP @ ^3.2.4
	mathieucarbou/ESPAsyncWebServer @ ^3.1.5
	alanswx/ESPAsyncWiFiManager@^0.31
	adafruit/Adafruit BME280 Library @ ^2.2.4
	paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0

; upload_protocol = espota

; [env:sensor_node_1]
; upload_port = 192.168.0.181

; [env:sensor_node_2]
; upload_port = 192.168.0.173
